/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingsystem;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DatabaseConnection;

/**
 *
 * @author ejave
 */
public class AdminInterface extends javax.swing.JFrame {

    private boolean adminPass = false;
    private boolean isEdit = false;
    private int id = 0;

    /**
     * Creates new form AdminInterface
     */
    public AdminInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("shs_election?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        candidatesQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Candidates c");
        candidatesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : candidatesQuery.getResultList();
        diagAdminPass = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAdminPass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCandidate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmbDiv = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbPos = new javax.swing.JComboBox<>();
        BSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCandidates = new javax.swing.JTable();

        diagAdminPass.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please enter admin passcode:");

        txtAdminPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminPassActionPerformed(evt);
            }
        });
        txtAdminPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diagAdminPassLayout = new javax.swing.GroupLayout(diagAdminPass.getContentPane());
        diagAdminPass.getContentPane().setLayout(diagAdminPassLayout);
        diagAdminPassLayout.setHorizontalGroup(
            diagAdminPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diagAdminPassLayout.setVerticalGroup(
            diagAdminPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELECTORAL POSITION");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Candidate Name");

        txtCandidate.setBackground(new java.awt.Color(35, 46, 65));
        txtCandidate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCandidate.setForeground(new java.awt.Color(255, 255, 255));
        txtCandidate.setBorder(null);
        txtCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCandidateActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Division");

        cmbDiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STEM", "ABM", "HUMSS", "TECHVOC" }));
        cmbDiv.setSelectedIndex(-1);
        cmbDiv.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Position");

        cmbPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "President", "Vice President", "Governor", "Vice Governor", "Representative", "Board Member" }));
        cmbPos.setSelectedIndex(-1);
        cmbPos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BSubmit.setText("SUBMIT");
        BSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSubmitActionPerformed(evt);
            }
        });

        tblCandidates.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblCandidates.setRowHeight(30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, candidatesList, tblCandidates);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${candidatename}"));
        columnBinding.setColumnName("Candidate Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${division}"));
        columnBinding.setColumnName("Division");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${position}"));
        columnBinding.setColumnName("Position");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblCandidates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCandidatesMouseClicked(evt);
            }
        });
        tblCandidates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCandidatesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCandidates);
        if (tblCandidates.getColumnModel().getColumnCount() > 0) {
            tblCandidates.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblCandidates.getColumnModel().getColumn(1).setResizable(false);
            tblCandidates.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BSubmit)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbPos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jSeparator1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(189, 189, 189))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSubmit)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSubmitActionPerformed
        // TODO add your handling code here:
        //verify admin
        adminPass = false;
        diagAdminPass.pack();
        diagAdminPass.setLocationRelativeTo(this);
        diagAdminPass.setVisible(true);

        if (!adminPass) {
            JOptionPane.showMessageDialog(this, "Please enter correct authorization code");
            return;
        }

        //check fields
        if (txtCandidate.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter candidate name");
            return;
        }

        if (cmbDiv.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Select proper division");
            return;
        }
        if (cmbPos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Select proper position");
            return;
        }

        Connection c = DatabaseConnection.getDatabaseConnection();
        //check record
        try {
            PreparedStatement ps = c.prepareStatement("SELECT * FROM candidates WHERE CANDIDATENAME = ? AND DIVISION=? AND POSITION=?");
            ps.setString(1, txtCandidate.getText().trim());
            ps.setString(2, cmbDiv.getSelectedItem().toString().trim());
            ps.setString(3, cmbPos.getSelectedItem().toString().trim());
            ResultSet results = ps.executeQuery();
            results.beforeFirst();
            if (results.next()) {
                JOptionPane.showMessageDialog(this, "Duplicate record found!");
                return;
            }

            if (isEdit) {
                System.out.println(id);
                PreparedStatement pEdit = c.prepareStatement("UPDATE candidates SET CANDIDATENAME = ?, DIVISION= ?, POSITION=? WHERE ID = ?");
                pEdit.setString(1, txtCandidate.getText().trim());
                pEdit.setString(2, cmbDiv.getSelectedItem().toString().trim());
                pEdit.setString(3, cmbPos.getSelectedItem().toString().trim());
                pEdit.setInt(4, id);
                pEdit.executeUpdate();
                JOptionPane.showMessageDialog(this, "Candidate information updated.");
                isEdit = false;
            } else {
                ps = c.prepareStatement("INSERT INTO candidates(CANDIDATENAME, DIVISION, POSITION) VALUES (?,?,?)");
                ps.setString(1, txtCandidate.getText().trim());
                ps.setString(2, cmbDiv.getSelectedItem().toString().trim());
                ps.setString(3, cmbPos.getSelectedItem().toString().trim());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Candidate successfully added!");
            }

            txtCandidate.setText("");
            cmbDiv.setSelectedIndex(-1);
            cmbPos.setSelectedIndex(-1);
            txtAdminPass.setText("");

        } catch (Exception ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtAdminPass.setText("");

        refreshTable();
    }//GEN-LAST:event_BSubmitActionPerformed

    private void txtAdminPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminPassKeyPressed
        // TODO add your handling code here:
        String adminpass = "cjcshs";
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Arrays.equals(txtAdminPass.getPassword(), adminpass.toCharArray())) {
                adminPass = true;
                diagAdminPass.dispose();
            } else {
                JOptionPane.showMessageDialog(diagAdminPass, "PLease enter correct authorization code.");
                adminPass = false;
            }
        }

    }//GEN-LAST:event_txtAdminPassKeyPressed

    private void txtAdminPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminPassActionPerformed

    private void tblCandidatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCandidatesMouseClicked
        try {
            // TODO add your handling code here:
            String name = tblCandidates.getValueAt(tblCandidates.getSelectedRow(), 0).toString();
            String div = tblCandidates.getValueAt(tblCandidates.getSelectedRow(), 1).toString();
            String pos = tblCandidates.getValueAt(tblCandidates.getSelectedRow(), 2).toString();

            txtCandidate.setText(name);
            cmbPos.setSelectedItem(pos);
            cmbDiv.setSelectedItem(div);

            Connection c = DatabaseConnection.getDatabaseConnection();
            PreparedStatement ps = c.prepareStatement("SELECT * FROM candidates WHERE CANDIDATENAME = ? AND DIVISION=? AND POSITION=?");
            ps.setString(1, txtCandidate.getText().trim());
            ps.setString(2, cmbDiv.getSelectedItem().toString().trim());
            ps.setString(3, cmbPos.getSelectedItem().toString().trim());
            ResultSet results = ps.executeQuery();
            results.beforeFirst();
            if (results.next()) {
                id = results.getInt("ID");
            }

            isEdit = true;
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblCandidatesMouseClicked

    private void tblCandidatesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCandidatesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            //verify admin
            adminPass = false;
            diagAdminPass.pack();
            diagAdminPass.setLocationRelativeTo(this);
            diagAdminPass.setVisible(true);

            if (!adminPass) {
                JOptionPane.showMessageDialog(this, "Please enter correct authorization code");
                return;
            }

            try {
                Connection c = DatabaseConnection.getDatabaseConnection();
                PreparedStatement pDelete = c.prepareStatement("DELETE FROM candidates WHERE CANDIDATENAME = ? AND DIVISION=? AND POSITION=?");
                pDelete.setString(1, txtCandidate.getText().trim());
                pDelete.setString(2, cmbDiv.getSelectedItem().toString().trim());
                pDelete.setString(3, cmbPos.getSelectedItem().toString().trim());
                pDelete.executeUpdate();

                candidatesList = candidatesQuery.getResultList();
                org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, candidatesList, tblCandidates);
                org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${candidatename}"));
                columnBinding.setColumnName("Candidate Name");
                columnBinding.setColumnClass(String.class);
                columnBinding.setEditable(false);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${division}"));
                columnBinding.setColumnName("Division");
                columnBinding.setColumnClass(String.class);
                columnBinding.setEditable(false);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${position}"));
                columnBinding.setColumnName("Position");
                columnBinding.setColumnClass(String.class);
                columnBinding.setEditable(false);
                bindingGroup.addBinding(jTableBinding);
                jTableBinding.bind();
            } catch (SQLException ex) {
                Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblCandidatesKeyPressed

    private void txtCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCandidateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCandidateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSubmit;
    private java.util.List<votingsystem.Candidates> candidatesList;
    private javax.persistence.Query candidatesQuery;
    private javax.swing.JComboBox<String> cmbDiv;
    private javax.swing.JComboBox<String> cmbPos;
    private javax.swing.JDialog diagAdminPass;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCandidates;
    private javax.swing.JPasswordField txtAdminPass;
    private javax.swing.JTextField txtCandidate;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {

        tblCandidates = new javax.swing.JTable();

        tblCandidates.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tblCandidates.setRowHeight(30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, candidatesList, tblCandidates);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${candidatename}"));
        columnBinding.setColumnName("Candidate Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${division}"));
        columnBinding.setColumnName("Division");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${position}"));
        columnBinding.setColumnName("Position");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblCandidates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCandidatesMouseClicked(evt);
            }
        });
        tblCandidates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCandidatesKeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(tblCandidates);

        if (tblCandidates.getColumnModel().getColumnCount() > 0) {
            tblCandidates.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblCandidates.getColumnModel().getColumn(1).setResizable(false);
            tblCandidates.getColumnModel().getColumn(2).setResizable(false);
        }

    }

}
